#!/bin/sh

. /etc/os-release
. /lib/functions/uci-defaults.sh

devices_setup()
{
    case $(uname -m) in
    aarch64)
        uci set irqbalance.irqbalance.enabled='0'
        uci commit irqbalance
        service irqbalance stop
        [ ! -d "/usr/share/openwrt_core" ] && {
            sed -i '/openwrt_core/d' /etc/opkg/distfeeds.conf
            sed -i "\$a\src/gz openwrt_core https://openwrt-lite.pages.dev/openwrt_core/23.05/aarch64_generic/$(grep Version /usr/lib/opkg/info/kernel.control | awk '{print $2}')" /etc/opkg/distfeeds.conf
        }
        ;;
    x86_64)
        [ -f /sys/kernel/btf/vmlinux ] && [ ! -d "/usr/share/openwrt_core" ] && {
            sed -i '/openwrt_core/d' /etc/opkg/distfeeds.conf
            sed -i "\$a\src/gz openwrt_core https://openwrt-lite.pages.dev/openwrt_core/23.05/x86_64/$(grep Version /usr/lib/opkg/info/kernel.control | awk '{print $2}')" /etc/opkg/distfeeds.conf
        }
        ;;
    esac
}

# opkg mirror
sed -i 's,downloads.openwrt.org,mirrors.aliyun.com/openwrt,g' /etc/opkg/distfeeds.conf
echo "src/gz repo_base https://openwrt-lite.pages.dev/openwrt_base/23.05/$(. /etc/openwrt_release ; echo $DISTRIB_ARCH)" >> /etc/opkg/distfeeds.conf
echo "src/gz repo_extd https://openwrt-lite.pages.dev/openwrt_extd/23.05/$(. /etc/openwrt_release ; echo $DISTRIB_ARCH)" >> /etc/opkg/distfeeds.conf
echo "src/gz repo_lite https://openwrt-lite.pages.dev/openwrt_lite/23.05/$(. /etc/openwrt_release ; echo $DISTRIB_ARCH)" >> /etc/opkg/distfeeds.conf
[ ! -f /etc/opkg/keys/65e5c9185ca12c26 ] && echo -e 'untrusted comment: Local build key\nRWRl5ckYXKEsJontRs89DQXo5UCG3v8yRTtlWHOvyIJL2qalpj8j6kfR' > /etc/opkg/keys/65e5c9185ca12c26

# banner
[[ $(grep -c 'pmkol' /usr/lib/lua/luci/view/themes/argon/footer.htm) -eq 0 ]] && [[ $(grep -c 'openwrt-lite.pages.dev' /etc/banner) -eq 0 ]] && sed -i '/OpenWrt/a \ \n Powered by OpenWrt-Lite. More info on our homepage:\n https://openwrt-lite.pages.dev/' /etc/banner

# theme
if [ -z "$(uci -q get luci.main.pollinterval)" ]; then
    uci set luci.main.mediaurlbase='/luci-static/argon'
    uci set luci.main.pollinterval='3'
    uci commit luci
fi

# timezone
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

# log level
uci set system.@system[0].conloglevel='1'
uci set system.@system[0].cronloglevel='9'
uci commit system

# zram
mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
zram_size=$(echo | awk "{print int($mem_total*0.25/1024)}")
uci set system.@system[0].zram_size_mb="$zram_size"
uci set system.@system[0].zram_comp_algo='zstd'
uci commit system

# docker mirror
if [ -f /etc/config/dockerd ] && [ $(grep -c daocloud.io /etc/config/dockerd) -eq '0' ]; then
    uci add_list dockerd.globals.registry_mirrors="https://docker.m.daocloud.io"
    uci commit dockerd
fi

# firewall
[ $(grep -c shortcut_fe /etc/config/firewall) -eq '0' ] && uci set firewall.@defaults[0].flow_offloading='1'
if [ $(ifconfig -a | grep -o '^eth[^ ]*' | wc -l) -le 1 ]; then
    uci set firewall.@zone[1].input='ACCEPT'
fi
uci set firewall.@defaults[0].input='ACCEPT'
uci commit firewall

# diagnostics
if [ $(uci -q get luci.diag.ping) = "openwrt.org" ]; then
    uci set luci.diag.dns='www.qq.com'
    uci set luci.diag.ping='www.qq.com'
    uci set luci.diag.route='www.qq.com'
    uci commit luci
fi

# packet steering
uci -q get network.globals.packet_steering > /dev/null || {
    uci set network.globals='globals'
    uci set network.globals.packet_steering=1
    uci commit network
}

# create opt
[ ! -d "/opt" ] && mkdir /opt

# disable coremark
sed -i '/coremark/d' /etc/crontabs/root
crontab /etc/crontabs/root

# scheduled upgrade
grep -q "opkg upgrade" /etc/crontabs/root || echo "#0 5 * * * opkg update && opkg list-upgradable | grep -vE '(luci-base|luci-mod-)' | awk '{print \$1}' | xargs opkg upgrade" >> /etc/crontabs/root

# init
devices_setup

exit 0
