--- luci-app-dockerman/Makefile
+++ luci-app-dockerman/Makefile
@@ -6,7 +6,8 @@ LUCI_DEPENDS:=@(aarch64||arm||x86_64) \
 	+luci-compat \
 	+luci-lib-docker \
 	+docker \
-	+ttyd
+	+ttyd \
+	+dockerd
 
 PKG_LICENSE:=AGPL-3.0
 PKG_MAINTAINER:=lisaac <lisaac.cn@gmail.com> \
